# First run
# echo HOST_ADDR=$(curl -s https://api.ipify.org) > .env && docker-compose up -d && docker-compose exec -d dockovpn wget -O /doc/Dockovpn/client.ovpn localhost:8080

version: '3'
services:
  dockovpn:
    build: ../Dockerfile
    image: alekslitvinenk/openvpn
    cap_add:
        - NET_ADMIN
    ports:
        - 1194:1194/udp
    expose:
        - "8080"
    environment:
        HOST_ADDR: ${HOST_ADDR} 
    volumes:
        - ./openvpn_conf:/doc/Dockovpn
    restart: always
  nginx: 
    image: nginx
    ports:
        - "80:80"
    volumes:
        - "./nginx/htpasswd://etc/nginx/htpasswd"
        - "./nginx/default.conf:/etc/nginx/sites-eanbled/default.conf"
    
    
     
